"""Initial migration with FKs

Revision ID: af7b0768c4e9
Revises: 
Create Date: 2026-05-06 20:50:00.532475+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import shared.encryption.fields
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af7b0768c4e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key (server-generated)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Server-side timestamp of the action (cannot be client-supplied)'),
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='UUID of the actor (user.id, admin.id, or null for system actions)'),
    sa.Column('actor_type', sa.String(length=50), nullable=False, comment='Actor classification: user | admin | system | webhook | celery_task'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action verb: loan.status_changed | user.suspended | kyc.verified | disbursement.initiated | repayment.received | penalty.applied | ...'),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment="Affected entity table name (e.g. 'loans', 'users', 'kyc_records')"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='UUID of the affected entity row'),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="State diff: {before: {status: 'pending_review'}, after: {status: 'approved'}}. PII fields must be excluded from diff payloads."),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6) from the triggering request'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='HTTP User-Agent from the triggering request'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='Correlation request ID for tracing through distributed logs'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Free-text context (e.g. reviewer rejection reason)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('account_number', shared.encryption.fields.EncryptedString(length=512), nullable=False, comment='AES-256-GCM encrypted NUBAN account number'),
    sa.Column('account_number_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash for duplicate detection without decryption'),
    sa.Column('bank_code', sa.String(length=10), nullable=False, comment="CBN bank/institution code (e.g. '044' for Access Bank)"),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='Bank name for display purposes'),
    sa.Column('account_name', sa.String(length=255), nullable=False, comment='Account holder name as returned by bank verification (NIBSS/Paystack)'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Whether this is the primary account for repayments'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='True when account name verified via bank API'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of bank account verification'),
    sa.Column('mono_account_id', sa.String(length=255), nullable=True, comment='Mono account ID if linked via Mono open banking'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bank_code', 'account_number_hash', name='uq_bank_accounts_user_bank_account')
    )
    op.create_index(op.f('ix_bank_accounts_account_number_hash'), 'bank_accounts', ['account_number_hash'], unique=False)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('consent_type', sa.String(length=100), nullable=False, comment='Type of consent: terms_and_conditions | privacy_policy | credit_check | data_sharing_bureau | marketing | data_sharing_mono'),
    sa.Column('granted', sa.Boolean(), nullable=False, comment='True = consent granted, False = consent withheld or revoked'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address at time of consent action'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of consent action (grant or initial withholding)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when consent was subsequently revoked (null if still active)'),
    sa.Column('version', sa.String(length=20), nullable=True, comment="Version of the terms/policy document consented to (e.g. 'v1.2')"),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Capture surface: mobile_app | admin_dashboard | api'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_consent_type'), 'consent_records', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('identity_documents',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('doc_type', sa.Enum('NIN_SLIP', 'VOTERS_CARD', 'DRIVERS_LICENSE', 'INTERNATIONAL_PASSPORT', 'UTILITY_BILL', 'CAC_CERTIFICATE', name='doc_type'), nullable=False, comment='Category of the identity document'),
    sa.Column('s3_key', sa.String(length=1024), nullable=False, comment='GCS object key (path within the KYC bucket). Never a public URL.'),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='OCR/extraction results from the document (name, DOB, ID number, etc.)'),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='OCR extraction confidence score (0.0000–1.0000)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False if superseded by a later upload of the same doc_type'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_documents_user_id'), 'identity_documents', ['user_id'], unique=False)
    op.create_table('kyc_records',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id (one KYC record per user)'),
    sa.Column('bvn_hash', shared.encryption.fields.EncryptedString(length=512), nullable=True, comment='AES-256-GCM encrypted BVN value — NEVER plaintext'),
    sa.Column('nin_hash', shared.encryption.fields.EncryptedString(length=512), nullable=True, comment='AES-256-GCM encrypted NIN value — NEVER plaintext'),
    sa.Column('bvn_verified', sa.Boolean(), nullable=False, comment='True when BVN verified by a KYC provider'),
    sa.Column('nin_verified', sa.Boolean(), nullable=False, comment='True when NIN verified by a KYC provider'),
    sa.Column('selfie_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Liveness + face-match confidence score (0.0000–1.0000)'),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'VERIFIED', 'FAILED', name='kyc_status'), nullable=False, comment='Aggregate KYC verification status'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when all required verifications passed'),
    sa.Column('identity_confidence', sa.Numeric(precision=5, scale=4), nullable=True, comment='Composite identity confidence score used in risk scoring (0.0–1.0)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_records_user_id'), 'kyc_records', ['user_id'], unique=True)
    op.create_table('loan_products',
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable product name (e.g. 'QuickCash 14')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Product description shown to borrowers'),
    sa.Column('min_amount', sa.Integer(), nullable=False, comment='Minimum loan amount in Naira'),
    sa.Column('max_amount', sa.Integer(), nullable=False, comment='Maximum loan amount in Naira — hard cap at ₦25,000 (Phase 1)'),
    sa.Column('min_tenor', sa.Integer(), nullable=False, comment='Minimum loan tenor in days'),
    sa.Column('max_tenor', sa.Integer(), nullable=False, comment='Maximum loan tenor in days — hard cap at 30 (Phase 1)'),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='Flat interest rate as a decimal (e.g. 0.0500 = 5%)'),
    sa.Column('fees', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Fee schedule'),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Eligibility constraints'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this product is currently available'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='E.164 format Nigerian phone number (primary login identifier)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Optional email address'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='Argon2id password hash — never store plaintext'),
    sa.Column('role', sa.Enum('BORROWER', 'AGENT', 'REVIEWER', 'ADMIN', 'SUPERADMIN', name='user_role'), nullable=False, comment='Platform role controlling RBAC access'),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='user_status'), nullable=False, comment='Account lifecycle state'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('verification_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Verification call timestamp'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('verification_type', sa.Enum('BVN', 'NIN', 'SELFIE', 'BANK', 'ADDRESS', name='verification_type'), nullable=False, comment='Type of verification performed'),
    sa.Column('provider', sa.Enum('YOUVERIFY', 'DOJAH', 'MONO', 'PAYSTACK', 'INTERNAL', name='verification_provider'), nullable=False, comment='Third-party KYC provider used'),
    sa.Column('result', sa.String(length=50), nullable=False, comment="Outcome: 'pass', 'fail', 'error', 'inconclusive'"),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full JSON response from provider (PII masked before storage)'),
    sa.Column('reference_id', sa.String(length=255), nullable=True, comment="Provider's reference/request ID for tracing"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_logs_user_id'), 'verification_logs', ['user_id'], unique=False)
    op.create_table('admin_users',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Staff display name for the admin UI'),
    sa.Column('role', sa.Enum('BORROWER', 'AGENT', 'REVIEWER', 'ADMIN', 'SUPERADMIN', name='user_role'), nullable=False, comment='Mirrors users.role — denormalised for quick admin queries'),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True, comment="Fine-grained permission flags (e.g. ['approve_loans', 'view_reports'])"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this admin account is currently active'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp for audit purposes'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Organisational department (e.g. Risk, Collections, Operations)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_user_id'), 'admin_users', ['user_id'], unique=True)
    op.create_table('borrower_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Legal full name as on government ID'),
    sa.Column('dob', sa.DateTime(), nullable=True, comment='Date of birth (date only — time component ignored)'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True, comment='Residential address (free text)'),
    sa.Column('state_of_residence', sa.String(length=100), nullable=True, comment='Nigerian state of residence'),
    sa.Column('employer', sa.String(length=255), nullable=True, comment='Current employer or business name'),
    sa.Column('employment_type', sa.String(length=100), nullable=True, comment='e.g. salaried, self-employed, POS operator, logistics, student'),
    sa.Column('monthly_income', sa.Integer(), nullable=True, comment='Declared monthly income in Naira (kobo not used here)'),
    sa.Column('bvn_verified', sa.Boolean(), nullable=False, comment='Whether BVN has been verified by a KYC provider'),
    sa.Column('nin_verified', sa.Boolean(), nullable=False, comment='Whether NIN has been verified by a KYC provider'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_profiles_user_id'), 'borrower_profiles', ['user_id'], unique=True)
    op.create_table('device_fingerprints',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_fingerprints_device_hash'), 'device_fingerprints', ['device_hash'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_user_id'), 'device_fingerprints', ['user_id'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='fraud_severity'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_flags_flag_type'), 'fraud_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_fraud_flags_user_id'), 'fraud_flags', ['user_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id (applicant)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='FK → loan_products.id'),
    sa.Column('requested_amount', sa.Integer(), nullable=False, comment='Amount requested by borrower in Naira'),
    sa.Column('approved_amount', sa.Integer(), nullable=True, comment='Amount approved by reviewer'),
    sa.Column('tenor', sa.Integer(), nullable=False, comment='Requested repayment tenor in days'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'BUREAU_PENDING', 'SCORING', 'PENDING_REVIEW', 'APPROVED', 'AGREEMENT_PENDING', 'AGREEMENT_SIGNED', 'DISBURSE_PENDING', 'DISBURSED', 'ACTIVE', 'PARTIALLY_REPAID', 'FULLY_REPAID', 'OVERDUE', 'WRITTEN_OFF', 'REJECTED', name='loan_application_status'), nullable=False, comment='Current state in the loan lifecycle'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='When the borrower formally submitted the application'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='FK → users.id (reviewer)'),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of approve/reject decision'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Reviewer notes'),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_product_id'), 'loan_applications', ['product_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_status'), 'loan_applications', ['status'], unique=False)
    op.create_index(op.f('ix_loan_applications_user_id'), 'loan_applications', ['user_id'], unique=False)
    op.create_table('credit_bureau_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('CRC', 'FIRST_CENTRAL', 'INTERNAL', name='bureau_provider'), nullable=False),
    sa.Column('raw_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('active_loans', sa.Integer(), nullable=True),
    sa.Column('delinquencies', sa.Integer(), nullable=True),
    sa.Column('total_outstanding', sa.Integer(), nullable=True),
    sa.Column('pulled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_bureau_reports_application_id'), 'credit_bureau_reports', ['application_id'], unique=False)
    op.create_index(op.f('ix_credit_bureau_reports_user_id'), 'credit_bureau_reports', ['user_id'], unique=False)
    op.create_table('loans',
    sa.Column('application_id', sa.UUID(), nullable=False, comment='FK → loan_applications.id'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('principal', sa.Integer(), nullable=False, comment='Disbursed principal in Naira'),
    sa.Column('interest', sa.Integer(), nullable=False, comment='Total interest charge'),
    sa.Column('fees', sa.Integer(), nullable=False),
    sa.Column('total_due', sa.Integer(), nullable=False),
    sa.Column('amount_repaid', sa.Integer(), nullable=False),
    sa.Column('outstanding_balance', sa.Integer(), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PARTIALLY_REPAID', 'FULLY_REPAID', 'OVERDUE', 'WRITTEN_OFF', 'CANCELLED', name='loan_status'), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_application_id'), 'loans', ['application_id'], unique=True)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bureau_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bank_behaviour_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('internal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('identity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('behavioural_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_tier', sa.Enum('A', 'B', 'C', 'D', name='risk_tier'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_amount', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_application_id'), 'risk_scores', ['application_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_user_id'), 'risk_scores', ['user_id'], unique=False)
    op.create_table('collection_notes',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('contact_method', sa.String(length=50), nullable=True),
    sa.Column('next_follow_up', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_notes_agent_id'), 'collection_notes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_collection_notes_loan_id'), 'collection_notes', ['loan_id'], unique=False)
    op.create_table('disbursements',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('destination_account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INITIATED', 'SUCCESS', 'FAILED', 'REVERSED', name='disbursement_status'), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference'),
    sa.UniqueConstraint('reference', name='uq_disbursements_reference')
    )
    op.create_index(op.f('ix_disbursements_loan_id'), 'disbursements', ['loan_id'], unique=False)
    op.create_table('escalation_logs',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('escalated_by', sa.UUID(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_logs_loan_id'), 'escalation_logs', ['loan_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', 'IN_APP', 'PUSH', name='notification_channel'), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'BOUNCED', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_loan_id'), 'notifications', ['loan_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('penalties',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('waived', sa.Boolean(), nullable=False),
    sa.Column('waived_by', sa.UUID(), nullable=True),
    sa.Column('waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalties_loan_id'), 'penalties', ['loan_id'], unique=False)
    op.create_table('promise_to_pay',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('promised_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'KEPT', 'BROKEN', 'EXPIRED', name='ptp_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('broken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promise_to_pay_borrower_id'), 'promise_to_pay', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_promise_to_pay_loan_id'), 'promise_to_pay', ['loan_id'], unique=False)
    op.create_table('repayment_schedules',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'WAIVED', name='schedule_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayment_schedules_loan_id'), 'repayment_schedules', ['loan_id'], unique=False)
    op.create_table('repayments',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=False),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference'),
    sa.UniqueConstraint('payment_reference', name='uq_repayments_payment_reference')
    )
    op.create_index(op.f('ix_repayments_loan_id'), 'repayments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_repayments_schedule_id'), 'repayments', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayments_schedule_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_loan_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_repayment_schedules_loan_id'), table_name='repayment_schedules')
    op.drop_table('repayment_schedules')
    op.drop_index(op.f('ix_promise_to_pay_loan_id'), table_name='promise_to_pay')
    op.drop_index(op.f('ix_promise_to_pay_borrower_id'), table_name='promise_to_pay')
    op.drop_table('promise_to_pay')
    op.drop_index(op.f('ix_penalties_loan_id'), table_name='penalties')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_loan_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_escalation_logs_loan_id'), table_name='escalation_logs')
    op.drop_table('escalation_logs')
    op.drop_index(op.f('ix_disbursements_loan_id'), table_name='disbursements')
    op.drop_table('disbursements')
    op.drop_index(op.f('ix_collection_notes_loan_id'), table_name='collection_notes')
    op.drop_index(op.f('ix_collection_notes_agent_id'), table_name='collection_notes')
    op.drop_table('collection_notes')
    op.drop_index(op.f('ix_risk_scores_user_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_application_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_application_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_credit_bureau_reports_user_id'), table_name='credit_bureau_reports')
    op.drop_index(op.f('ix_credit_bureau_reports_application_id'), table_name='credit_bureau_reports')
    op.drop_table('credit_bureau_reports')
    op.drop_index(op.f('ix_loan_applications_user_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_status'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_product_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_fraud_flags_user_id'), table_name='fraud_flags')
    op.drop_index(op.f('ix_fraud_flags_flag_type'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_device_fingerprints_user_id'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_device_hash'), table_name='device_fingerprints')
    op.drop_table('device_fingerprints')
    op.drop_index(op.f('ix_borrower_profiles_user_id'), table_name='borrower_profiles')
    op.drop_table('borrower_profiles')
    op.drop_index(op.f('ix_admin_users_user_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_verification_logs_user_id'), table_name='verification_logs')
    op.drop_table('verification_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('loan_products')
    op.drop_index(op.f('ix_kyc_records_user_id'), table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_index(op.f('ix_identity_documents_user_id'), table_name='identity_documents')
    op.drop_table('identity_documents')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_consent_type'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_number_hash'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
